### ISSUE TITLE
Can I steal some of your code?

### ISSUE THREAD

**Issue by tlienart** [vitskvara/EvalCurves.jl#2]
Hello!

sorry for the cheeky question, in MLJBase.jl we have a bunch of metrics for binary classifiers including AUC and ROC but a user mentioned we didn't have the PRCurve which you do have. Would you be ok with us adapting some of your code (with due creds of course). I'm asking because you haven't set a License file. 

Btw we'd be delighted to have your help to improve/extend the metrics in MLJBase if that's something you would be interested in :) 

Thanks!

**Comment by pevnak** [comment]
Consider to steal it from this one, as it is a successor and more unit tested.
https://github.com/VaclavMacha/EvalMetrics.jl
Also, you can contact my student
@Sheemon7,
who is updating EvalMetrics.jl. He is putting some work on this library right now.

**Comment by vitskvara** [comment]
Hi,
yes, go ahead and steal either from me or from EvalMetrics.jl, whichever implementation suits you more :).

I'll try to take a look at MLJBase and let you know.

V.

**Comment by tlienart** [comment]
Good stuff. @vitskvara by the looks of it EvalMetrics has large overlap with the finite measures in MLJBase

* confusion matrix: https://github.com/alan-turing-institute/MLJBase.jl/blob/master/src/measures/confusion_matrix.jl
* metrics for discrete stuff: https://github.com/alan-turing-institute/MLJBase.jl/blob/master/src/measures/finite.jl

So  for instance we both have code for confusion matrix, TPR, FPR, and all those, F-B AUC, ROC, sensitivity etc. You do have a lot more extra stuff for specialised things which I'd be very interested in porting over :+1: . But I thought you might be interested in joining forces?

One thing to note is it is on our agenda to refactor the metrics on our side to make it an independent package compatible with MLJ so this could maybe be a good time to gather forces and, while I would understand you might not have a lot of time to dedicate to it, feedback is always appreciated.

Thanks both! (and I'll close this here but feel free to  reach out on Slack or at MLJBase)
